name: custom-whats-app

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  mongo:
    image: mongo
    container_name: mongo-whats-app
    networks:
      - app
    env_file: mongo.env
    ports:
      - '0.0.0.0:${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - db-data:/data

  mongo-express:
    image: mongo-express
    container_name: mongo-express-whats-app
    networks:
      - app
    ports:
      - '0.0.0.0:8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_WEB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_WEB_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_PORT: '27017'
    env_file: mongo.env
    depends_on:
      - mongo
